### ISSUE TITLE
Провести анализ алгоритмов реализации метода QUICK и QUICKEST помимо Leonardo

### ISSUE THREAD

**Issue by Nikita1526** [victorsouth/pde_solvers#20]
Найти и зафиксировать алгоритмы рализации методов QUICK и QUICKEST в других источниках

**Comment by victorsouth** [comment]
Выяснено по 2011 Neumann, что QUICK действительно сильно подвержен осцилляциям
QUICKEST в меньшей степени, но тоже подвержен.
В итоге пришли к тому, что надо реализовывать QUICKEST+ULTIMATE, что было сделано в рамках другого тикета
